# ===================================================#
#        MobSpawnTimer - V1.0.0 插件config檔
#                 by Y2-Dev / #雞槌勒
#       擊殺排行 / 運算區塊 / 排行獎勵 / 倒數重生PAPI
# ===================================================#

# ⭐ 是否啟用除錯模式（顯示詳細 LOG 輸出）
# 開啟後，後台會顯示玩家進入/離開區域的詳細資訊 (慎用...控制台會狂刷並偵測玩家移動相關訊息)
debug: false

# 💾 音效相關設定 (最大音量，可自行調整，預設 1.0 = 正常 / 0.5 = 一半音量...)
sound:
  fade:
    max-volume: 1.0

# 💾 指令相關設定 (進入/離開區域時，是否由執行指令)，(false = 以後台執行指令 / true  = 玩家以OP身分執行指令)
commands:
  as-player: false

# 💾 區域劃線工具設定材質以及介紹
wand:
  material: BLAZE_ROD # 劃線工具的材質 (只影響創建區域用)，原生同材質物品，不會有任何效果
  name: "&6&l區域劃線工具"
  lore:
    - ""
    - "&7左鍵點選方塊設為 &aA點"
    - "&7右鍵點選方塊設為 &bB點"

# 💬 Title顯示的時間 (當玩家進入或離開區域)，(單位 = 20 ticks = 1 秒)
title:
  # 出現時間 (單位 = 20 ticks = 1 秒)
  fade-in: 10  # Title 淡入時間
  stay: 40     # Title 停留時間
  fade-out: 10 # Title 淡出時間

# ⚠️ 區域內部系統設定 (無箱關data/save.yml設定)
region: # 玩家移動多少格才觸發偵測 (預設 1)
  check-distance: 2 # 1=每一格就偵測 (預設為2+=可稍微減少效能消耗)